### ISSUE TITLE
the second  def is not executing

### ISSUE THREAD

**Issue by sindhupath** [kying18/guess-the-number#4]
the program runs normally with user guess, but then it comes to the computer guess it doesn't work....could u tell what might be the mistake.thanks for the help.

**Comment by jkeenntt** [comment]
Have you tried changing what function you are calling? if you followed this code it would mean changing 

"guess(10)" 

to 

"computer_guess(10)"

**Comment by sindhupath** [comment]
yes i have realized it after i read through the code,thank you!
